### PR TITLE
Fix LM optimization script importing non existing function and add CI testing

### LINKED ISSUE #2202: Bug: lm_optimize throws error
Hi

I've tried it a couple of different ways and `lm_optimize()` always comes back that `lm_opt` is not defined, as below.

I tried `python -m coqui_stt_training.util.lm_optimize` as well with the same error.

mike h

```
python lm_optimizer.py --test_files /mhdata/cvnew/clips/tst.csv --checkpoint_dir fordata/mhwelsh/welsh/checkpoints --n_hidden 200 --scorer_path fordata/newwelsh.scorer
Using the top level lm_optimizer.py script is deprecated and will be removed in a future release. Instead use: python -m coqui_stt_training.util.lm_optimize
2022-04-24 22:22:02.584403: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
2022-04-24 22:22:04.263143: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299965000 Hz
2022-04-24 22:22:04.265496: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x53a4130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-04-24 22:22:04.265560: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-04-24 22:22:04.271188: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-04-24 22:22:05.976601: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:05.976833: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58bdfd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-04-24 22:22:05.976853: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 2080 Super with Max-Q Design, Compute Capability 7.5
2022-04-24 22:22:05.977046: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:05.977177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: NVIDIA GeForce RTX 2080 Super with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.08
pciBusID: 0000:01:00.0
2022-04-24 22:22:05.977214: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-04-24 22:22:05.988396: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-04-24 22:22:06.017602: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-04-24 22:22:06.018920: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-04-24 22:22:06.022358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2022-04-24 22:22:06.035457: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2022-04-24 22:22:06.035625: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-04-24 22:22:06.035725: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:06.035919: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:06.036020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0
2022-04-24 22:22:06.036259: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-04-24 22:22:07.039992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-04-24 22:22:07.040027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0
2022-04-24 22:22:07.040034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N
2022-04-24 22:22:07.040481: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:07.040668: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:07.040809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/device:GPU:0 with 6660 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Super with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
I --alphabet_config_path not specified, but found an alphabet file alongside specified checkpoint (fordata/mhwelsh/welsh/checkpoints/alphabet.txt). Will use this alphabet file for this run.
Traceback (most recent call last):
  File "lm_optimizer.py", line 16, in <module>
    lm_optimize.main()
  File "/code/training/coqui_stt_training/util/lm_optimize.py", line 86, in main
    results = lm_opt.compute_lm_optimization()
NameError: name 'lm_opt' is not defined
```

### PR DESCRIPTION
**Pull request by wasertech**
Remove `lm_opt` from `training.util.lm_optimize`. This should fix #2202

### CODE REVIEW

**Comment by reuben** [comment]
Can you add a test that does a very small LM optimization run in the extra training tests [here](https://github.com/coqui-ai/STT/blob/e2a7f79b047ddfb1391a646e1cea4ce593b9cea8/.github/workflows/build-and-test.yml#L801)? You should be able to add a new script in `bin` that calls the script and then reference that script in the GitHub Actions workflow, similar to the other tests already there. Thanks for the PR!

**Comment by wasertech** [comment]
[Much better indeed](https://gist.github.com/wasertech/1e116d654ce59bfe423aeb745839ac65).

**Comment by reuben** [comment]
And now you can get remote the flags.txt gitignore entry.

**Comment by wasertech** [comment]
> And now you can get remote the flags.txt gitignore entry.

Sorry what?

**Comment by reuben** [comment]
Sorry for that, I was replying on my phone and missed the typos.

**Pull request merged**
