### PR TITLE
Add docqa to docs website

### PR DESCRIPTION
**Pull request by nomagick**
Preview: 
https://stt--2156.org.readthedocs.build/en/2156/

Previously docqa was removed due to broken links.
Now the broken links have been fixed.

Also, customize the badge position to dodge the version selector this time. 
CleanShot 2022-03-08 at 00 26 00@2x

Effectively reverts 29fcf83794709ef9c60fab906b4141da8cd7809b

### CODE REVIEW

**Comment by reuben** [comment]
Some of the anchors seem to be broken. After searching for "How to install STT?" I get an answer with [this context link](https://stt--2156.org.readthedocs.build/en/2156/TRAINING_INTRO.html#installation:~:text=virtual%20environment) which doesn't skip to the section nor highlight the text. On the other hand when searching for "How to speed up training?" I get an answer with [this context link](https://stt--2156.org.readthedocs.build/en/2156/MIXED_PRECISION.html#automatic-mixed-precision:~:text=On%20a%20Volta%20generation%20V100%20GPU) which does work.

**Comment by reuben** [comment]
The added file is also missing a newline (we have [pre-commit checks](https://github.com/coqui-ai/STT/blob/main/CONTRIBUTING.rst#code-linting) in the repo which you can enable to check commits automatically).

**Comment by nomagick** [comment]
@reuben Thanks for the feedback!
Both context link actually works in Chromium-based browsers.

The context link is based on [Text Fragments](https://wicg.github.io/scroll-to-text-fragment/), an experimental browser feature.

Currently, only Chromium-based browsers natively support this.
For Safari and Firefox, this is done by a modified [polyfill](https://github.com/GoogleChromeLabs/text-fragments-polyfill).
There are some behaviour differences between the native impl and the polyfill.

For these three very questions, I have managed to walk around the issue In our latest release.

Please clear the browser cache, reload and try again.

**Comment by reuben** [comment]
@nomagick Safari and Firefox users represent around 40% of our documentation readers. Sphinx provides native anchors for sections, could your code be modified to find the nearest anchor and link to that, in addition to using text fragments/the polyfill? That way you get graceful degradation of behavior when the polyfill fails (which seems to be a 100% of the time in my tests).

**Comment by sarachebbi** [comment]
> 
@nomagick will check and get back to you

**Comment by nomagick** [comment]
Ok, I did some tricks to mimic the Chromium behaviour when the polyfill is used.
You can test in Incognito mode to see the effect.

**Pull request merged**
