### PR TITLE
Update dotnet client to support netstandard2.0, netstandard2.1, net5.0 and net6.0

### PR DESCRIPTION
**Pull request by stepkillah**
Migrate to netstandard2.0 and add support for net5.0, net6.0
Also, I updated net461 to net48 because 4.6.1 is out of support

does the new repo have configured pipelines for dotnet? I only found an old one that uses taskcluster

### CODE REVIEW

**Comment by stepkillah** [comment]
> Thanks for the PR!
> 
> > does the new repo have configured pipelines for dotnet? I only found an old one that uses taskcluster
> 
> We do not. The .NET CI is still missing from the GitHub Actions transition.

I can try to add ones in this or better in separate PR later

**Comment by reuben** [comment]
That'd be fantastic!

**Comment by reuben** [comment]
Looks like there are some linter errors, could you [set-up the linter](https://github.com/coqui-ai/STT/blob/main/CONTRIBUTING.rst#code-linting) and run it on your files? You should be able to run `python .pre-commit-2.11.1.pyz run --all-files` to have it fix the problem for you, then `git commit --amend` and force push.

**Comment by stepkillah** [comment]
@reuben sorry, missed doing amend and did another commit :(

**Pull request merged**
