### PR TITLE
Add docqa to docs website

### PR DESCRIPTION
**Pull request by hanxiao**
Preview: https://stt--jina-docs.netlify.app/

### CODE REVIEW

**Comment by reuben** [comment]
Thanks for the PR! @JRMeyer do you have opinions on what the suggested questions should be?

@hanxiao the "See context" links are broken, could you take a look?

**Comment by deepankarm** [comment]
> Thanks for the PR! @JRMeyer do you have opinions on what the suggested questions should be?
> 
> @hanxiao the "See context" links are broken, could you take a look?

@reuben We've fixed the issue with `See context` links. Could you please check again?

**Comment by reuben** [comment]
@deepankarm nice, seems to be working for me now!

**Comment by reuben** [comment]
@hanxiao can you allow access to the PR branch to the STT contributors? I want to push a fix for the broken build on RTD.

**Comment by hanxiao** [comment]
@reuben just invited you. I haven't figured out how to do that in bulk

**Comment by reuben** [comment]
Thanks, that works! But FWIW I meant just for this PR, there should be a checkbox on the right sidebar somewhere: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by hanxiao** [comment]
Tried so hard to find that checkbox, but turns out https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/7

This PR comes from our @Jina-AI account so 🤷

**Comment by reuben** [comment]
@hanxiao well, the collaborator access worked too. PR looks good, I'll wait for Josh's comment on the default questions and merge.

**Comment by hanxiao** [comment]
Yay! thanks! btw, we have another one at https://github.com/coqui-ai/TTS/pull/1315  but doc-build part seems fine?

**Pull request merged**
