### PR TITLE
Fix #1955 Use local source instead of redownloading in Dockerfile.build

### LINKED ISSUE #1955: Bug: Dockerfile.build redownloads the entire source code
**Describe the bug**
When running `docker build -f Dockerfile.build .` from the STT directory, `Dockerfile.build` redownloads the entire STT source code, instead of using the existing source code.

**To Reproduce**
Clone STT source code with git
Make some commits / check out the tag you want to build
`docker build -f Dockerfile.build .`

**Expected behavior**
The Dockerfile would build the source that exists in the STT directory, including any changes that have been made to the source.

**Actual behaviour**
The Dockerfile downloads a fresh version of the source and builds that. This is unexpected and unintuitive, and a waste of disk space, bandwidth and time.

### PR DESCRIPTION
**Pull request by jeremiahrose**
Make Dockerfile.build copy the current checked out source code into the Docker image instead of downloading a fresh clone.
This was useful to me, saved time and effort and allowed me to easily build the specific tag / commit that I was working on at the time.

### CODE REVIEW

**Comment by reuben** [comment]
Thanks for the PR! Could you update the corresponding docs in `doc/DEPLOYMENT.rst`? And maybe add a job to CI that builds this? You can see the existing `docker-publish` job for inspiration. If you don't have the time for the CI part just give me a heads up and I'll merge with just the docs update!

**Comment by jeremiahrose** [comment]
Updated the doc! Don't have time for CI scripts right now so maybe you should merge. Might have some time after #1954 and #1953

**Comment by jeremiahrose** [comment]
Updated the doc! Don't have time for CI scripts right now so maybe you should merge.

**Review by reuben — APPROVED** [review]
Thanks!

**Pull request merged**
